version: '3.0'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'devops-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    networks:
      devops-network:

  devops-project:
    build: .\
    image: devops-project
    container_name: "devops-project-service"
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devops-db
    networks:
      devops-network:

networks:
  devops-network:
    driver: bridge