version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'devops-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'